name: Weekly Lotto Update

on:
  schedule:
    - cron: '30 12 * * 6' # 한국 시간 매주 토요일 밤 9시 30분
  workflow_dispatch: # 직접 실행하고 싶을 때 사용

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Update JSON
        run: python update_lotto.py
      - name: Commit changes
        run: |
          git config --global user.name "LottoBot"
          git config --global user.email "bot@github.com"
          git add lotto_recent_year.json
          git commit -m "Update: Latest 10 Lotto Rounds" || echo "No changes to commit"
          git push
