name: Auto Update Lotto

on:
  schedule:
    - cron: '0 12 * * 6' # 매주 토요일 실행
  workflow_dispatch:      # 수동 실행 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run script
        run: python update_lotto.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add lotto_recent_year.json
          git commit -m "Update lotto data" || echo "No changes to commit"
          git push
